name: login_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^1.3.3
  curved_navigation_bar: ^0.3.7
  http: ^0.13.3
  form_field_validator: ^1.1.0
  fluttertoast: ^8.0.8
  flutter_session: ^0.1.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.0+4
  flutter_local_notifications: ^4.0.1+2
  favorite_button: ^0.0.4
  flutter_typeahead: ^1.7.0
  late_init: ^1.1.0
  geolocator: ^5.1.5
  permission_handler: ^3.0.1
  google_maps_flutter: ^0.5.19
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
