name: login_ui
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  simple_animations: ^1.3.3
  curved_navigation_bar: ^0.3.7
  http: ^0.13.3
  image_picker: ^0.8.1
  form_field_validator: ^1.1.0
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
   

flutter:
  uses-material-design: true

  assets:
    - assets/images/